const express = require('express');
const cors = require('cors');
const crypto = require('crypto');

const app = express();
app.use(cors());
app.use(express.json());

// In-Memory Meter Registry storing Public Keys (DER-HEX format)
const generatorRegistry = {
  "GEN-MUTARE-001": {
    name: "Mutare Solar Array",
    // Paste the public key generated by your client/hardware here
    publicKeyHex: null, 
    balance: 120.00,
    totalKwh: 2400
  }
};

// Replay Attack Cache (Store used nonces)
const processedNonces = new Set();
const REWARD_RATE_PER_KWH = 0.05;

/**
 * Utility: Reconstruct public key object from HEX
 */
function getPublicKeyFromHex(hexString) {
  return crypto.createPublicKey({
    key: Buffer.from(hexString, 'hex'),
    format: 'der',
    type: 'spki'
  });
}

/**
 * POST /api/energy/submit
 * Validates cryptographic signatures prior to minting rewards.
 */
app.post('/api/energy/submit', (req, res) => {
  const { generatorId, kwhGenerated, timestamp, nonce, signature } = req.body;

  // 1. Basic validation
  if (!generatorId || !kwhGenerated || !timestamp || !nonce || !signature) {
    return res.status(400).json({ error: "Missing required payload fields or cryptographic signature." });
  }

  const generator = generatorRegistry[generatorId];
  if (!generator || !generator.publicKeyHex) {
    return res.status(403).json({ error: "Generator ID not registered or missing public key." });
  }

  // 2. Prevent Replay Attacks (Check timestamp drift & nonces)
  const now = new Date().getTime();
  const payloadTime = new Date(timestamp).getTime();
  const FIVE_MINUTES_MS = 5 * 60 * 1000;

  if (Math.abs(now - payloadTime) > FIVE_MINUTES_MS) {
    return res.status(401).json({ error: "Rejected: Telemetry timestamp expired or out of sync." });
  }

  if (processedNonces.has(nonce)) {
    return res.status(401).json({ error: "Rejected: Replay attack detected. Nonce already processed." });
  }

  // 3. Reconstruct canonical message string
  const canonicalMessage = `${generatorId}:${kwhGenerated}:${timestamp}:${nonce}`;

  // 4. Verify Signature against registered Public Key
  try {
    const publicKey = getPublicKeyFromHex(generator.publicKeyHex);
    const isValid = crypto.verify(
      null,
      Buffer.from(canonicalMessage),
      publicKey,
      Buffer.from(signature, 'hex')
    );

    if (!isValid) {
      return res.status(401).json({ error: "Signature verification failed. Data tampered or key mismatch." });
    }
  } catch (err) {
    return res.status(500).json({ error: "Cryptographic verification error: " + err.message });
  }

  // 5. Mark nonce as used
  processedNonces.add(nonce);

  // 6. Execute Minting
  const rewardAmount = parseFloat((kwhGenerated * REWARD_RATE_PER_KWH).toFixed(4));
  generator.balance = parseFloat((generator.balance + rewardAmount).toFixed(4));
  generator.totalKwh += kwhGenerated;

  const txHash = "0x" + crypto.randomBytes(16).toString('hex');

  console.log(`[VERIFIED MINT] ${rewardAmount} TATI issued to ${generatorId} (Tx: ${txHash})`);

  return res.json({
    status: "SUCCESS",
    message: "Cryptographic signature verified. Tati Coins minted.",
    txHash,
    rewardAmount,
    newBalance: generator.balance
  });
});

app.listen(3001, () => {
  console.log("Secure Minting API running on http://localhost:3001");
});